name: aurora
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 数据
  flutter_blue: ^0.8.0
  dio: any
  http: any
  flutter_mobx: ^2.0.0
  get: ^4.3.8

  # 持久化
  shared_preferences: ^2.0.5
  moor: ^4.5.0
  sqlite3_flutter_libs: ^0.5.0

  # UI
  bot_toast: ^4.0.1
  flutter_colorpicker: ^0.6.0
  lottie: ^1.0.1
  flutter_svg: ^0.21.0+1
  flutter_slidable: ^0.6.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.5.2
  fl_chart: ^0.40.0
  floating_action_bubble:
    git:
      url: https://github.com/simonkimi/FloatingActionBubble
      ref: ^2.0.0

  # 工具
  path_provider: ^2.0.0
  path: ^1.8.0
  synchronized: ^3.0.0
  protobuf: ^2.0.0
  vibration: ^1.7.4-nullsafety.0
  event_bus: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3
  moor_generator: ^4.5.1
  build_runner: ^2.1.1



flutter:
  uses-material-design: true

  assets:
    - assets/lottie/
    - assets/svg/
    - assets/img/